package com.lanshark.software.security.accountmanager.gui;

import javax.swing.*;
import java.awt.*;

public class PasswordGeneratorDialog extends JDialog
{

    private JPanel mainPanel;
    private JPanel allowedPanel;
    private JCheckBox useLowercaseCheckBox;
    private JCheckBox useUppercaseCheckBox;
    private JCheckBox useNumbersCheckBox;
    private JCheckBox checkBox4;
    private JCheckBox checkBox5;
    private JCheckBox $CheckBox;
    private JCheckBox checkBox2;
    private JCheckBox checkBox3;
    private JCheckBox checkBox6;
    private JCheckBox checkBox7;
    private JCheckBox checkBox8;
    private JCheckBox checkBox1;
    private JCheckBox checkBox9;
    private JCheckBox _CheckBox;
    private JCheckBox checkBox11;
    private JCheckBox checkBox12;
    private JCheckBox checkBox13;
    private JCheckBox checkBox14;
    private JCheckBox checkBox10;
    private JCheckBox checkBox15;
    private JCheckBox checkBox16;
    private JCheckBox checkBox17;
    private JCheckBox checkBox18;
    private JCheckBox checkBox19;
    private JCheckBox checkBox20;
    private JCheckBox checkBox21;
    private JCheckBox checkBox22;
    private JCheckBox checkBox23;
    private JCheckBox checkBox24;
    private JCheckBox checkBox25;
    private JCheckBox checkBox26;
    private JCheckBox checkBox27;
    private JCheckBox checkBox28;
    private JButton removeAllButton;
    private JButton selectAllButton;
    private JPanel numbersPanel;
    private JSlider slider1;
    private JSpinner spinner1;
    private JButton resetButton;
    private JTextField textField1;
    private JButton generateButton;
    private JButton copyButton;
    private JPanel sliderPanel;

    public PasswordGeneratorDialog()
    {
        setContentPane(mainPanel);
        setModal(true);
        setTitle("Password Generator");

        // call onCancel() when cross is clicked
        this.pack();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setMinimumSize(new Dimension(600, 350));
        mainPanel.setPreferredSize(new Dimension(600, 350));
        allowedPanel = new JPanel();
        allowedPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        allowedPanel.setAlignmentY(0.5f);
        allowedPanel.setMinimumSize(new Dimension(200, 0));
        allowedPanel.setPreferredSize(new Dimension(200, 350));
        mainPanel.add(allowedPanel, BorderLayout.WEST);
        allowedPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        useLowercaseCheckBox = new JCheckBox();
        useLowercaseCheckBox.setText("Use Lowercase?");
        allowedPanel.add(useLowercaseCheckBox);
        useUppercaseCheckBox = new JCheckBox();
        useUppercaseCheckBox.setText("Use Uppercase?");
        allowedPanel.add(useUppercaseCheckBox);
        useNumbersCheckBox = new JCheckBox();
        useNumbersCheckBox.setText("Use Numbers?");
        allowedPanel.add(useNumbersCheckBox);
        final JSeparator separator1 = new JSeparator();
        separator1.setMinimumSize(new Dimension(190, 2));
        separator1.setPreferredSize(new Dimension(190, 2));
        allowedPanel.add(separator1);
        checkBox4 = new JCheckBox();
        checkBox4.setText("@");
        allowedPanel.add(checkBox4);
        checkBox5 = new JCheckBox();
        checkBox5.setText("#");
        allowedPanel.add(checkBox5);
        $CheckBox = new JCheckBox();
        $CheckBox.setText("$");
        allowedPanel.add($CheckBox);
        checkBox2 = new JCheckBox();
        checkBox2.setText("%");
        allowedPanel.add(checkBox2);
        checkBox3 = new JCheckBox();
        checkBox3.setText("^");
        allowedPanel.add(checkBox3);
        checkBox6 = new JCheckBox();
        checkBox6.setText("");
        allowedPanel.add(checkBox6);
        checkBox7 = new JCheckBox();
        checkBox7.setText("*");
        allowedPanel.add(checkBox7);
        checkBox8 = new JCheckBox();
        checkBox8.setText("(");
        allowedPanel.add(checkBox8);
        checkBox1 = new JCheckBox();
        checkBox1.setText(")");
        allowedPanel.add(checkBox1);
        checkBox9 = new JCheckBox();
        checkBox9.setText("-");
        allowedPanel.add(checkBox9);
        _CheckBox = new JCheckBox();
        _CheckBox.setText("_");
        allowedPanel.add(_CheckBox);
        checkBox11 = new JCheckBox();
        checkBox11.setText("=");
        allowedPanel.add(checkBox11);
        checkBox12 = new JCheckBox();
        checkBox12.setText("+");
        allowedPanel.add(checkBox12);
        checkBox13 = new JCheckBox();
        checkBox13.setText("[");
        allowedPanel.add(checkBox13);
        checkBox14 = new JCheckBox();
        checkBox14.setText("]");
        allowedPanel.add(checkBox14);
        checkBox10 = new JCheckBox();
        checkBox10.setText("{");
        allowedPanel.add(checkBox10);
        checkBox15 = new JCheckBox();
        checkBox15.setText("}");
        allowedPanel.add(checkBox15);
        checkBox16 = new JCheckBox();
        checkBox16.setText("\\");
        allowedPanel.add(checkBox16);
        checkBox17 = new JCheckBox();
        checkBox17.setText("/");
        allowedPanel.add(checkBox17);
        checkBox18 = new JCheckBox();
        checkBox18.setText("|");
        allowedPanel.add(checkBox18);
        checkBox19 = new JCheckBox();
        checkBox19.setText("<");
        allowedPanel.add(checkBox19);
        checkBox20 = new JCheckBox();
        checkBox20.setPreferredSize(new Dimension(34, 22));
        checkBox20.setText(">");
        allowedPanel.add(checkBox20);
        selectAllButton = new JButton();
        selectAllButton.setText("Select All");
        allowedPanel.add(selectAllButton);
        removeAllButton = new JButton();
        removeAllButton.setText("Remove All");
        allowedPanel.add(removeAllButton);
        final JSeparator separator2 = new JSeparator();
        separator2.setMinimumSize(new Dimension(190, 2));
        separator2.setPreferredSize(new Dimension(190, 2));
        allowedPanel.add(separator2);
        checkBox21 = new JCheckBox();
        checkBox21.setText(";");
        allowedPanel.add(checkBox21);
        checkBox22 = new JCheckBox();
        checkBox22.setText(":");
        allowedPanel.add(checkBox22);
        checkBox23 = new JCheckBox();
        checkBox23.setText("'");
        allowedPanel.add(checkBox23);
        checkBox24 = new JCheckBox();
        checkBox24.setText("\"");
        allowedPanel.add(checkBox24);
        checkBox25 = new JCheckBox();
        checkBox25.setText(",");
        allowedPanel.add(checkBox25);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setMinimumSize(new Dimension(25, 0));
        panel1.setPreferredSize(new Dimension(25, 0));
        allowedPanel.add(panel1);
        checkBox26 = new JCheckBox();
        checkBox26.setText(".");
        allowedPanel.add(checkBox26);
        checkBox27 = new JCheckBox();
        checkBox27.setText("?");
        allowedPanel.add(checkBox27);
        checkBox28 = new JCheckBox();
        checkBox28.setText("!");
        allowedPanel.add(checkBox28);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel2.setMinimumSize(new Dimension(25, 0));
        panel2.setPreferredSize(new Dimension(25, 0));
        allowedPanel.add(panel2);
        final JButton button1 = new JButton();
        button1.setText("Select All");
        allowedPanel.add(button1);
        final JButton button2 = new JButton();
        button2.setText("Remove All");
        allowedPanel.add(button2);
        numbersPanel = new JPanel();
        numbersPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 10));
        numbersPanel.setMinimumSize(new Dimension(200, 0));
        numbersPanel.setPreferredSize(new Dimension(200, 0));
        mainPanel.add(numbersPanel, BorderLayout.EAST);
        numbersPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JLabel label1 = new JLabel();
        label1.setText("Password Length:");
        numbersPanel.add(label1);
        spinner1 = new JSpinner();
        spinner1.setPreferredSize(new Dimension(50, 22));
        numbersPanel.add(spinner1);
        sliderPanel = new JPanel();
        sliderPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        sliderPanel.setPreferredSize(new Dimension(190, 300));
        numbersPanel.add(sliderPanel);
        sliderPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JLabel label2 = new JLabel();
        label2.setText("Min. Lowercase:");
        sliderPanel.add(label2);
        final JLabel label3 = new JLabel();
        label3.setText("Label");
        sliderPanel.add(label3);
        slider1 = new JSlider();
        slider1.setPreferredSize(new Dimension(175, 22));
        sliderPanel.add(slider1);
        final JLabel label4 = new JLabel();
        label4.setText("Min. Uppercase:");
        sliderPanel.add(label4);
        final JLabel label5 = new JLabel();
        label5.setText("Label");
        sliderPanel.add(label5);
        final JSlider slider2 = new JSlider();
        slider2.setPreferredSize(new Dimension(175, 22));
        sliderPanel.add(slider2);
        final JLabel label6 = new JLabel();
        label6.setText("Min. Numbers:");
        sliderPanel.add(label6);
        final JLabel label7 = new JLabel();
        label7.setText("Label");
        sliderPanel.add(label7);
        final JSlider slider3 = new JSlider();
        slider3.setPreferredSize(new Dimension(175, 22));
        sliderPanel.add(slider3);
        final JLabel label8 = new JLabel();
        label8.setText("Min. Special:");
        sliderPanel.add(label8);
        final JLabel label9 = new JLabel();
        label9.setText("Label");
        sliderPanel.add(label9);
        final JSlider slider4 = new JSlider();
        slider4.setPreferredSize(new Dimension(175, 22));
        sliderPanel.add(slider4);
        final JLabel label10 = new JLabel();
        label10.setText("Min. Punctuation:");
        sliderPanel.add(label10);
        final JLabel label11 = new JLabel();
        label11.setText("Label");
        sliderPanel.add(label11);
        final JSlider slider5 = new JSlider();
        slider5.setPreferredSize(new Dimension(175, 22));
        sliderPanel.add(slider5);
        resetButton = new JButton();
        resetButton.setText("Reset");
        sliderPanel.add(resetButton);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 55));
        mainPanel.add(panel3, BorderLayout.CENTER);
        final JLabel label12 = new JLabel();
        label12.setText("Password");
        panel3.add(label12);
        textField1 = new JTextField();
        textField1.setPreferredSize(new Dimension(200, 24));
        panel3.add(textField1);
        generateButton = new JButton();
        generateButton.setPreferredSize(new Dimension(85, 25));
        generateButton.setText("Generate");
        panel3.add(generateButton);
        copyButton = new JButton();
        copyButton.setPreferredSize(new Dimension(85, 25));
        copyButton.setText("Copy");
        panel3.add(copyButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }
}
